name: Release

on:
  push:
    tags:
      - 'release/*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: flrapp/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ghcr.io/flrapp/flare-api
      dockerfile-path: ./src/Flare.Api/Dockerfile
    secrets: inherit
